Repository WildCodeSchool/orleans-0918-php-cafes-eric, pull requests merged in 2018-11, with the labels that each got.

#1 Ajout webpackEncore et librairies
  .env
  .gitignore
  assets/.gitignore
  assets/css/app.scss
  assets/css/template/_about.scss
  assets/css/template/_bootstrap-overrides.scss
  assets/css/template/_buttons.scss
  assets/css/template/_cta.scss
  assets/css/template/_footer.scss
  assets/css/template/_global.scss
  assets/css/template/_intro.scss
  assets/css/template/_mixins.scss
  assets/css/template/_navbar.scss
  assets/css/template/_products.scss
  assets/css/template/_store.scss
  assets/css/template/_variables.scss
  assets/css/template/business-casual.scss
  assets/js/app.js
  composer.json
  composer.lock
  config/bundles.php
  config/packages/assets.yaml
  config/packages/webpack_encore.yaml
  package.json
  symfony.lock
  templates/base.html.twig
  webpack.config.js
  yarn.lock
Labels: Correction Done, Reviewed by PO

#13 Ajout layout
  templates/base.html.twig
  templates/layout.html.twig
  templates/layoutAdmin.html.twig
Labels: Reviewed by PO

#15 Dev to Master
  .env
  .gitignore
  assets/.gitignore
  assets/css/app.scss
  assets/css/template/_about.scss
  assets/css/template/_bootstrap-overrides.scss
  assets/css/template/_buttons.scss
  assets/css/template/_cta.scss
  assets/css/template/_footer.scss
  assets/css/template/_global.scss
  assets/css/template/_intro.scss
  assets/css/template/_mixins.scss
  assets/css/template/_navbar.scss
  assets/css/template/_products.scss
  assets/css/template/_store.scss
  assets/css/template/_variables.scss
  assets/css/template/business-casual.scss
  assets/js/app.js
  composer.json
  composer.lock
  config/bundles.php
  config/packages/assets.yaml
  config/packages/webpack_encore.yaml
  package.json
  symfony.lock
  templates/base.html.twig
  templates/layout.html.twig
  templates/layoutAdmin.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed by PO

#18 Création navbar
  assets/css/app.scss
  assets/css/template/_global.scss
  assets/css/template/_variables.scss
  templates/layout.html.twig
  templates/navbar.html.twig
Labels: Reviewed by PO

#19 Dev to Master
  assets/css/app.scss
  assets/css/template/_global.scss
  assets/css/template/_variables.scss
  templates/layout.html.twig
  templates/navbar.html.twig
Labels: Reviewed by PO

#17 Sprint01 us11
  assets/css/app.scss
  assets/css/category.scss
  assets/css/template/_intro.scss
  assets/css/variables.scss
  assets/images/teaImages/presentation_tea.jpg
  assets/js/app.js
  src/Controller/TeaCategoryController.php
  templates/base.html.twig
  templates/teaCategory/index.html.twig
Labels: Reviewed by PO

#22 Dev to Master
  assets/css/app.scss
  assets/css/category.scss
  assets/css/template/_intro.scss
  assets/css/variables.scss
  assets/images/teaImages/presentation_tea.jpg
  assets/js/app.js
  src/Controller/TeaCategoryController.php
  templates/base.html.twig
  templates/teaCategory/index.html.twig
Labels: Reviewed by PO

#20 S1us01
  assets/css/app.scss
  assets/css/global.scss
  assets/css/template/_global.scss
  assets/fonts/Lora/Lora-Bold.ttf
  assets/fonts/Lora/Lora-BoldItalic.ttf
  assets/fonts/Lora/Lora-Italic.ttf
  assets/fonts/Lora/Lora-Regular.ttf
  assets/fonts/Lora/OFL.txt
  assets/fonts/Raleway/OFL.txt
  assets/fonts/Raleway/Raleway-Black.ttf
  assets/fonts/Raleway/Raleway-BlackItalic.ttf
  assets/fonts/Raleway/Raleway-Bold.ttf
  assets/fonts/Raleway/Raleway-BoldItalic.ttf
  assets/fonts/Raleway/Raleway-ExtraBold.ttf
  assets/fonts/Raleway/Raleway-ExtraBoldItalic.ttf
  assets/fonts/Raleway/Raleway-ExtraLight.ttf
  assets/fonts/Raleway/Raleway-ExtraLightItalic.ttf
  assets/fonts/Raleway/Raleway-Italic.ttf
  assets/fonts/Raleway/Raleway-Light.ttf
  assets/fonts/Raleway/Raleway-LightItalic.ttf
  assets/fonts/Raleway/Raleway-Medium.ttf
  assets/fonts/Raleway/Raleway-MediumItalic.ttf
  assets/fonts/Raleway/Raleway-Regular.ttf
  assets/fonts/Raleway/Raleway-SemiBold.ttf
  assets/fonts/Raleway/Raleway-SemiBoldItalic.ttf
  assets/fonts/Raleway/Raleway-Thin.ttf
  assets/fonts/Raleway/Raleway-ThinItalic.ttf
  assets/images/homeImages/coffeBackGround.jpg
  assets/js/app.js
  src/Controller/HomeController.php
  templates/base.html.twig
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed by PO

#25 Sprint02 us06
  .travis.yml
  templates/home/index.html.twig
  templates/schedule.html.twig
Labels: Reviewed by PO

#23 Sprint01 us22
  assets/css/app.scss
  assets/css/footer.scss
  assets/css/variables.scss
  package.json
  templates/footer.html.twig
  templates/layout.html.twig
  yarn.lock
Labels: Reviewed by PO

#34 Dev
  assets/css/app.scss
  assets/css/footer.scss
  assets/css/variables.scss
  package.json
  templates/footer.html.twig
  templates/layout.html.twig
  yarn.lock
Labels: Reviewed by PO

#37 Sprint01 us22
  assets/css/app.scss
Labels: Reviewed by PO

#40 Sprint01 us10
  assets/css/category.scss
  assets/css/variables.scss
  assets/images/coffeeImages/coffee_beans.jpg
  assets/js/app.js
  src/Controller/CoffeeCategoryController.php
  templates/coffee_category/index.html.twig
  templates/teaCategory/index.html.twig
Labels: CONFLICT RESOLVED

#41 Sprint02 us06
  assets/css/app.scss
  assets/css/schedule.scss
  templates/layout.html.twig
  templates/schedule.html.twig
Labels: Correction Done, Reviewed by PO

#42 Sprint02 us05
  assets/css/app.scss
  assets/images/homeImages/storyBoutique.png
  templates/home/index.html.twig
  templates/story.html.twig
Labels: Reviewed by PO

#45 Prfix us11
  assets/css/app.scss
  assets/css/category.scss
  assets/css/variables.scss
  templates/teaCategory/index.html.twig
Labels: Reviewed by PO

#47 fix du style
  assets/css/category.scss
  assets/css/global.scss
  assets/css/variables.scss
  templates/coffee_category/index.html.twig
  templates/teaCategory/index.html.twig
Labels: Reviewed by PO

#43 SPRINT02_US30
  src/Controller/AdminHomeController.php
  templates/admin_home/index.html.twig
  templates/layoutAdmin.html.twig
  templates/navbarAdmin.html.twig
Labels: Correction Done, Reviewed by PO

#46 SRINT02_US40
  composer.json
  composer.lock
  config/bundles.php
  config/packages/twig.yaml
  src/Controller/CategoryController.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/ShelfFixtures.php
  src/Entity/Category.php
  src/Entity/Shelf.php
  src/Form/CategoryType.php
  src/Migrations/Version20181129094608.php
  src/Repository/CategoryRepository.php
  src/Repository/ShelfRepository.php
  symfony.lock
  templates/category/_delete_form.html.twig
  templates/category/_form.html.twig
  templates/category/edit.html.twig
  templates/category/index.html.twig
  templates/category/new.html.twig
  templates/category/show.html.twig
Labels: Correction Done, Reviewed by PO

#52 FIX_FONTS
  assets/fonts/Lora/Lora-Bold.ttf
  assets/fonts/Lora/Lora-BoldItalic.ttf
  assets/fonts/Lora/Lora-Italic.ttf
  assets/fonts/Lora/Lora-Regular.ttf
  assets/fonts/Lora/OFL.txt
  assets/fonts/Raleway/OFL.txt
  assets/fonts/Raleway/Raleway-Black.ttf
  assets/fonts/Raleway/Raleway-BlackItalic.ttf
  assets/fonts/Raleway/Raleway-Bold.ttf
  assets/fonts/Raleway/Raleway-BoldItalic.ttf
  assets/fonts/Raleway/Raleway-ExtraBold.ttf
  assets/fonts/Raleway/Raleway-ExtraBoldItalic.ttf
  assets/fonts/Raleway/Raleway-ExtraLight.ttf
  assets/fonts/Raleway/Raleway-ExtraLightItalic.ttf
  assets/fonts/Raleway/Raleway-Italic.ttf
  assets/fonts/Raleway/Raleway-Light.ttf
  assets/fonts/Raleway/Raleway-LightItalic.ttf
  assets/fonts/Raleway/Raleway-Medium.ttf
  assets/fonts/Raleway/Raleway-MediumItalic.ttf
  assets/fonts/Raleway/Raleway-Regular.ttf
  assets/fonts/Raleway/Raleway-SemiBold.ttf
  assets/fonts/Raleway/Raleway-SemiBoldItalic.ttf
  assets/fonts/Raleway/Raleway-Thin.ttf
  assets/fonts/Raleway/Raleway-ThinItalic.ttf
  templates/base.html.twig
Labels: Reviewed by PO

#51 Dev
  assets/css/contact.scss
  assets/css/global.scss
  assets/css/template/_global.scss
  assets/css/variables.scss
  assets/fonts/Lora/Lora-Bold.ttf
  assets/fonts/Lora/Lora-BoldItalic.ttf
  assets/fonts/Lora/Lora-Italic.ttf
  assets/fonts/Lora/Lora-Regular.ttf
  assets/fonts/Lora/OFL.txt
  assets/fonts/Raleway/OFL.txt
  assets/fonts/Raleway/Raleway-Black.ttf
  assets/fonts/Raleway/Raleway-BlackItalic.ttf
  assets/fonts/Raleway/Raleway-Bold.ttf
  assets/fonts/Raleway/Raleway-BoldItalic.ttf
  assets/fonts/Raleway/Raleway-ExtraBold.ttf
  assets/fonts/Raleway/Raleway-ExtraBoldItalic.ttf
  assets/fonts/Raleway/Raleway-ExtraLight.ttf
  assets/fonts/Raleway/Raleway-ExtraLightItalic.ttf
  assets/fonts/Raleway/Raleway-Italic.ttf
  assets/fonts/Raleway/Raleway-Light.ttf
  assets/fonts/Raleway/Raleway-LightItalic.ttf
  assets/fonts/Raleway/Raleway-Medium.ttf
  assets/fonts/Raleway/Raleway-MediumItalic.ttf
  assets/fonts/Raleway/Raleway-Regular.ttf
  assets/fonts/Raleway/Raleway-SemiBold.ttf
  assets/fonts/Raleway/Raleway-SemiBoldItalic.ttf
  assets/fonts/Raleway/Raleway-Thin.ttf
  assets/fonts/Raleway/Raleway-ThinItalic.ttf
  assets/images/homeImages/diagmonds-light.png
  config/packages/twig.yaml
  src/Controller/TeaCategoryController.php
  src/DataFixtures/AppFixtures.php
  templates/base.html.twig
  templates/footer.html.twig
  templates/navbar.html.twig
Labels: Reviewed by PO

#53 Sprint02 us77
  assets/css/app.scss
  assets/css/variables.scss
  assets/images/homeImages/worker2.jpeg
  composer.lock
  src/Controller/HomeController.php
  src/DataFixtures/WorkerFixtures.php
  src/Entity/Worker.php
  src/Migrations/Version20181128134925.php
  src/Migrations/Version20181130084928.php
  src/Repository/WorkerRepository.php
  symfony.lock
  templates/home/index.html.twig
  templates/worker.html.twig
Labels: Reviewed by PO

#54 Dev to master
  assets/css/app.scss
  assets/css/variables.scss
  assets/images/homeImages/worker2.jpeg
  composer.lock
  src/Controller/HomeController.php
  src/DataFixtures/WorkerFixtures.php
  src/Entity/Worker.php
  src/Migrations/Version20181128134925.php
  src/Migrations/Version20181130084928.php
  src/Repository/WorkerRepository.php
  symfony.lock
  templates/home/index.html.twig
  templates/worker.html.twig
Labels: Reviewed by PO
