Repository WildCodeSchool/orleans-0918-php-cafes-eric, pull requests merged in 2018-12, with the labels that each got.

#73 Sprint03 us66
  assets/css/admin.scss
  assets/css/app.scss
  src/Controller/AdminWorkerController.php
  src/Form/WorkerType.php
  src/Migrations/Version20181128134925.php
  src/Migrations/Version20181130084928.php
  templates/admin_worker/_delete_form.html.twig
  templates/admin_worker/_form.html.twig
  templates/admin_worker/edit.html.twig
  templates/admin_worker/index.html.twig
  templates/admin_worker/new.html.twig
  templates/admin_worker/show.html.twig
  templates/home/index.html.twig
  templates/navbarAdmin.html.twig
Labels: Correction Done, Reviewed by PO

#77 S02 us21
  src/Migrations/Version20181130115209.php
  templates/contact/index.html.twig
Labels: Reviewed by PO

#78 réparation de dev a cause d'un refactor
  templates/home/index.html.twig
Labels: Reviewed by PO

#88 Sprint03 us78
  templates/admin_worker/_form.html.twig
  templates/admin_worker/edit.html.twig
Labels: Reviewed by PO

#90 Stylisation de la page d'ajout
  src/Form/WorkerType.php
  templates/admin_worker/_form.html.twig
  templates/admin_worker/new.html.twig
Labels: Reviewed by PO

#93 Stylisation et modification de la page show
  templates/admin_worker/show.html.twig
Labels: Reviewed by PO

#95 Sprint03 us45
  templates/admin/subcategory/_form.html.twig
  templates/admin/subcategory/edit.html.twig
Labels: Reviewed by PO

#96 SPRINT03_US42
  src/Migrations/Version20181204094856.php
  templates/category/_delete_form.html.twig
  templates/category/_form.html.twig
  templates/category/edit.html.twig
Labels: Reviewed by PO

#99 SPRINT03_US82
  templates/category/index.html.twig
Labels: Reviewed by PO

#100 Sprint03 us44
  src/Form/SubcategoryType.php
  templates/admin/subcategory/new.html.twig
Labels: Reviewed by PO

#97 SPRINT03_US43
  templates/category/_delete_form.html.twig
Labels: Reviewed by PO

#101 Sprint03 us46
  templates/admin/subcategory/_delete_form.html.twig
Labels: Reviewed by PO

#123 Dev
  src/Controller/SubcategoryController.php
  src/Form/SubcategoryType.php
  src/Migrations/Version20181204094856.php
  templates/admin/subcategory/_delete_form.html.twig
  templates/admin/subcategory/_form.html.twig
  templates/admin/subcategory/edit.html.twig
  templates/admin/subcategory/new.html.twig
  templates/admin_worker/_delete_form.html.twig
  templates/category/_delete_form.html.twig
  templates/category/_form.html.twig
  templates/category/edit.html.twig
  templates/category/index.html.twig
Labels: Reviewed by PO

#136 fix sur la reception du mail
  src/Controller/ContactController.php
Labels: Reviewed by PO

#137 Dev
  src/Controller/ContactController.php
Labels: Reviewed by PO

#142 Sprint03 93
  assets/css/app.scss
  assets/css/map.scss
  assets/css/template/_store.scss
  templates/contact/index.html.twig
Labels: Reviewed by PO

#150 ajout des vérifictations serveur du formulaire et remise en forme du …
  src/Entity/Worker.php
  templates/admin_worker/_form.html.twig
Labels: CONFLICT RESOLVED

#151 ajout du nullable=true sur ls valeurs bool
  src/Entity/Tea.php
Labels: Reviewed by PO

#152 Sprint03 us60
  composer.json
  composer.lock
  phpunit.xml.dist
  src/Controller/WorkerController.php
  src/Migrations/Version20181128134925.php
  src/Migrations/Version20181130084928.php
  templates/admin/worker/_delete_form.html.twig
  templates/admin/worker/_form.html.twig
  templates/admin/worker/edit.html.twig
  templates/admin/worker/index.html.twig
  templates/admin/worker/new.html.twig
  templates/admin/worker/show.html.twig
Labels: CONFLICT RESOLVED, Reviewed by PO

#156 Sprint03 us31
  src/Controller/CoffeeController.php
  src/Controller/SubcategoryController.php
  src/Entity/Category.php
  src/Entity/Coffee.php
  src/Entity/Subcategory.php
  src/Form/CoffeeType.php
  src/Migrations/Version20181207100102.php
  src/Migrations/Version20181208071558.php
  src/Migrations/Version20181208143610.php
  src/Migrations/Version20181210160052.php
  src/Migrations/Version20181211085849.php
  src/Repository/CoffeeRepository.php
  templates/admin/coffee/_delete_form.html.twig
  templates/admin/coffee/_form.html.twig
  templates/admin/coffee/edit.html.twig
  templates/admin/coffee/index.html.twig
  templates/admin/coffee/new.html.twig
  templates/admin/coffee/show.html.twig
  templates/admin/subcategory/_delete_form.html.twig
  templates/admin/subcategory/_form.html.twig
  templates/admin/subcategory/edit.html.twig
  templates/admin/subcategory/index.html.twig
  templates/admin/subcategory/new.html.twig
  templates/admin/subcategory/show.html.twig
  templates/navbarAdmin.html.twig
Labels: Correction Done, Reviewed by PO

#166 Sprint03 us33
  templates/admin/coffee/_delete_form.html.twig
  templates/admin/coffee/_form.html.twig
Labels: Reviewed by PO

#170 Sprint03 us32
  templates/admin/coffee/edit.html.twig
Labels: Reviewed by PO

#171 SPRINT03_US86
  src/Controller/InfusionController.php
  src/Entity/Category.php
  src/Entity/Infusion.php
  src/Form/InfusionType.php
  src/Repository/InfusionRepository.php
  templates/admin/infusion/_delete_form.html.twig
  templates/admin/infusion/_form.html.twig
  templates/admin/infusion/edit.html.twig
  templates/admin/infusion/index.html.twig
  templates/admin/infusion/new.html.twig
  templates/admin/infusion/show.html.twig
Labels: Reviewed by PO

#172 modification de l'edit du thé
  src/Controller/TeaController.php
  templates/admin/tea/edit.html.twig
Labels: Reviewed by PO

#174 SPRINT03_US87
  src/Controller/InfusionController.php
  src/Migrations/Version20181128134925.php
  src/Migrations/Version20181129094608.php
  src/Migrations/Version20181130084928.php
  src/Migrations/Version20181130104722.php
  src/Migrations/Version20181130115209.php
  src/Migrations/Version20181204090735.php
  src/Migrations/Version20181204093115.php
  src/Migrations/Version20181204094856.php
  src/Migrations/Version20181204163630.php
  src/Migrations/Version20181204165106.php
  src/Migrations/Version20181205135247.php
  src/Migrations/Version20181205140547.php
  src/Migrations/Version20181205144515.php
  src/Migrations/Version20181205151820.php
  src/Migrations/Version20181206071927.php
  src/Migrations/Version20181206073904.php
  src/Migrations/Version20181206074414.php
  src/Migrations/Version20181207092228.php
  src/Migrations/Version20181207100102.php
  src/Migrations/Version20181208071558.php
  src/Migrations/Version20181208143610.php
  src/Migrations/Version20181210160052.php
  src/Migrations/Version20181211085849.php
  src/Migrations/Version20181212135729.php
  templates/admin/infusion/edit.html.twig
Labels: Reviewed by PO

#175 SPRINT03_US88
  src/Controller/InfusionController.php
  templates/admin/infusion/_delete_form.html.twig
Labels: Reviewed by PO

#176 Sprint03 us69
  templates/admin/tea/index.html.twig
  templates/navbarAdmin.html.twig
Labels: Reviewed by PO

#177 Sprint04 us91
  .travis.yml
  config/packages/security.yaml
  config/routes.yaml
  src/Controller/SecurityController.php
  src/Entity/User.php
  src/Migrations/Version20181212090849.php
  src/Repository/UserRepository.php
  src/Security/AppAdminAuthenticator.php
  templates/navbarAdmin.html.twig
  templates/security/login.html.twig
Labels: Correction Done, Reviewed by PO

#184 Sprint04 us96
  src/Controller/CoffeeController.php
  src/Twig/CountryExtension.php
  templates/admin/coffee/show.html.twig
Labels: Reviewed by PO

#185 SPRINT03_US92
  templates/admin/infusion/index.html.twig
  templates/navbarAdmin.html.twig
Labels: Reviewed by PO

#186 SPRINT03_US98
  templates/admin/infusion/show.html.twig
Labels: Reviewed by PO

#187 Dev to master à accepter apres les autres
  .travis.yml
  config/packages/security.yaml
  config/routes.yaml
  src/Controller/CoffeeController.php
  src/Controller/SecurityController.php
  src/Entity/User.php
  src/Migrations/Version20181212090849.php
  src/Repository/UserRepository.php
  src/Security/AppAdminAuthenticator.php
  src/Twig/CountryExtension.php
  templates/admin/coffee/show.html.twig
  templates/admin/infusion/index.html.twig
  templates/admin/infusion/show.html.twig
  templates/navbarAdmin.html.twig
  templates/security/login.html.twig
Labels: Reviewed by PO

#188 Sprint03 us70
  templates/admin/coffee/index.html.twig
Labels: Reviewed by PO

#189 Dev
  templates/admin/coffee/index.html.twig
Labels: Reviewed by PO

#195 ajout de la fonction delete
  src/Controller/TeaController.php
  templates/admin/tea/_delete_form.html.twig
  templates/admin/tea/index.html.twig
Labels: Reviewed by PO

#206 Sprint05 us104 fix navbar admin
  templates/navbarAdmin.html.twig
Labels: Reviewed by PO

#210 Fix us81
  templates/admin/worker/show.html.twig
Labels: Reviewed by PO

#205 SPRINT05_US56
  src/Entity/Infusion.php
  src/Form/CoffeeType.php
  src/Form/InfusionType.php
  src/Form/TeaType.php
  src/Migrations/Version20181217133434.php
Labels: Reviewed by PO

#215 Sprint04 us94
  src/Entity/FamilyTea.php
  src/Entity/Tea.php
  src/Form/TeaType.php
  src/Migrations/Version20181217145855.php
  src/Migrations/Version20181217150127.php
  src/Migrations/Version20181217150433.php
  src/Repository/FamilyTeaRepository.php
Labels: Reviewed by PO

#214 S04 us15
  assets/css/accessory.scss
  assets/css/app.scss
  assets/images/accessoryImages/artea.jpg
  assets/images/accessoryImages/bialetti.jpg
  assets/images/accessoryImages/bodum.jpg
  assets/images/accessoryImages/forlife.jpg
  assets/images/accessoryImages/jura.jpg
  assets/images/accessoryImages/logo.jpg
  src/Controller/AccessoryController.php
  templates/accessory/index.html.twig
  templates/navbar.html.twig
Labels: Reviewed by PO

#220 Dev to Master
  assets/css/accessory.scss
  assets/css/app.scss
  assets/images/accessoryImages/artea.jpg
  assets/images/accessoryImages/bialetti.jpg
  assets/images/accessoryImages/bodum.jpg
  assets/images/accessoryImages/forlife.jpg
  assets/images/accessoryImages/jura.jpg
  assets/images/accessoryImages/logo.jpg
  src/Controller/AccessoryController.php
  src/Controller/TeaController.php
  src/Entity/FamilyTea.php
  src/Entity/Infusion.php
  src/Entity/Tea.php
  src/Form/CoffeeType.php
  src/Form/InfusionType.php
  src/Form/TeaType.php
  src/Migrations/Version20181217133434.php
  src/Migrations/Version20181217145855.php
  src/Migrations/Version20181217150127.php
  src/Migrations/Version20181217150433.php
  src/Repository/FamilyTeaRepository.php
  templates/accessory/index.html.twig
  templates/admin/tea/_delete_form.html.twig
  templates/admin/tea/index.html.twig
  templates/admin/tea/show.html.twig
  templates/admin/worker/show.html.twig
  templates/navbar.html.twig
  templates/navbarAdmin.html.twig
Labels: Reviewed by PO

#208 SPRINT05_US58
  src/Entity/Infusion.php
  src/Entity/Tea.php
  src/Form/CoffeeType.php
  src/Form/InfusionType.php
  src/Form/TeaType.php
  src/Migrations/Version20181217141429.php
  src/Migrations/Version20181217142720.php
  templates/admin/coffee/show.html.twig
  templates/admin/infusion/show.html.twig
  templates/admin/tea/show.html.twig
Labels: Reviewed by PO

#219 Affichage des catégories de café
  src/Controller/CoffeeCategoryController.php
  src/Entity/Shelf.php
  src/Migrations/Version20181218144402.php
  templates/coffee_category/index.html.twig
Labels: Correction Done

#228 FIX_INFUSION_DEV
  assets/images/logo/logo.jpg
  src/Entity/Infusion.php
Labels: Reviewed by PO

#227 Dev to master
  assets/images/logo/logo.jpg
  src/Controller/CoffeeCategoryController.php
  src/Entity/Infusion.php
  src/Entity/Shelf.php
  src/Entity/Tea.php
  src/Form/CoffeeType.php
  src/Form/InfusionType.php
  src/Form/TeaType.php
  src/Migrations/Version20181217141429.php
  src/Migrations/Version20181217142720.php
  src/Migrations/Version20181218144402.php
  templates/admin/coffee/show.html.twig
  templates/admin/infusion/show.html.twig
  templates/admin/tea/show.html.twig
  templates/coffee_category/index.html.twig
Labels: Reviewed by PO

#221 changement des boutons retour
  templates/admin/coffee/_form.html.twig
  templates/admin/coffee/edit.html.twig
  templates/admin/coffee/index.html.twig
  templates/admin/coffee/new.html.twig
  templates/admin/coffee/show.html.twig
  templates/admin/infusion/_form.html.twig
  templates/admin/infusion/edit.html.twig
  templates/admin/infusion/index.html.twig
  templates/admin/infusion/new.html.twig
  templates/admin/infusion/show.html.twig
  templates/admin/tea/_form.html.twig
  templates/admin/tea/edit.html.twig
  templates/admin/tea/index.html.twig
  templates/admin/tea/new.html.twig
  templates/admin/worker/_form.html.twig
  templates/admin/worker/edit.html.twig
  templates/admin/worker/index.html.twig
  templates/admin/worker/new.html.twig
  templates/admin/worker/show.html.twig
Labels: CONFLICT RESOLVED
