Repository WildCodeSchool/orleans-0918-php-cafes-eric, pull requests merged in 2019-01, with the labels that each got.

#230 Sprint05 us103
  .gitignore
  assets/css/app.scss
  assets/css/form.scss
  assets/css/vich_image.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  src/Entity/Worker.php
  src/Form/WorkerType.php
  src/Migrations/Version20181212090849.php
  src/Migrations/Version20181212135729.php
  src/Migrations/Version20181217133434.php
  src/Migrations/Version20181217145855.php
  src/Migrations/Version20181217150127.php
  src/Migrations/Version20181217150433.php
  src/Migrations/Version20181231094617.php
  symfony.lock
  templates/admin/worker/show.html.twig
Labels: Reviewed by PO

#234 update de vich
  .gitignore
  config/packages/vich_uploader.yaml
  templates/admin/worker/show.html.twig
Labels: Reviewed by PO

#242 Sprint07_us105
  .gitignore
  config/packages/vich_uploader.yaml
  src/Entity/Coffee.php
  src/Form/CoffeeType.php
  src/Migrations/Version20190104105153.php
  templates/admin/coffee/show.html.twig
Labels: Correction Done, Reviewed by PO

#248 ajout d'un background-image sur le site
  assets/css/global.scss
  assets/images/homeImages/padded.png
Labels: Reviewed by PO

#246 Fix us103
  .gitignore
  src/Entity/Worker.php
Labels: CONFLICT RESOLVED, Reviewed by PO

#245 mise en page de la bannière
  assets/css/app.scss
  assets/css/banner.scss
  assets/images/banner/bg.jpg
  templates/banner.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
Labels: Correction Done, Reviewed by PO

#251 Dev
  .gitignore
  assets/css/app.scss
  assets/css/banner.scss
  assets/css/global.scss
  assets/images/banner/bg.jpg
  assets/images/homeImages/padded.png
  config/packages/vich_uploader.yaml
  src/Entity/Coffee.php
  src/Entity/Worker.php
  src/Form/CoffeeType.php
  src/Migrations/Version20190104105153.php
  templates/admin/coffee/show.html.twig
  templates/banner.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
Labels: Reviewed by PO

#249 Fix style us104
  .gitignore
  assets/css/category.scss
  templates/coffee_category/index.html.twig
Labels: CONFLICT RESOLVED, Reviewed by PO

#263 SPRINT08_US115
  src/Form/InfusionType.php
Labels: CONFLICT RESOLVED

#269 Fix gitkeep
  .gitignore
  public/upload/.gitkeep
Labels: CONFLICT RESOLVED

#271 Dev
  .gitignore
  assets/css/category.scss
  public/upload/.gitkeep
  src/Controller/CoffeeController.php
  src/Controller/InfusionController.php
  src/Controller/TeaController.php
  src/Form/CoffeeType.php
  src/Form/InfusionType.php
  src/Form/TeaType.php
  src/Migrations/Version20190103104331.php
  src/Migrations/Version20190107085231.php
  src/Migrations/Version20190107085453.php
  src/Migrations/Version20190107090512.php
  src/Service/MaxProductChecker.php
  templates/accessory/index.html.twig
  templates/admin/coffee/index.html.twig
  templates/admin/coffee/show.html.twig
  templates/admin/infusion/index.html.twig
  templates/admin/tea/index.html.twig
  templates/category/edit.html.twig
  templates/coffee_category/index.html.twig
  templates/grocery/index.html.twig
Labels: Reviewed by PO

#273 SPRINT07_US108
  src/Controller/CoffeeController.php
  src/Controller/InfusionController.php
  src/Controller/TeaController.php
  src/Service/MaxProductChecker.php
  templates/admin/coffee/index.html.twig
  templates/admin/infusion/index.html.twig
  templates/admin/tea/index.html.twig
Labels: Reviewed by PO

#277 Fix de Vich
  src/Controller/WorkerController.php
  src/Entity/Worker.php
Labels: Reviewed by PO

#278 Fix images
  assets/js/app.js
  templates/accessory/index.html.twig
  templates/grocery/index.html.twig
Labels: Reviewed by PO

#280 Fix story
  templates/story.html.twig
Labels: Reviewed by PO

#281 ajout des photos worker sur la vue visiteur
  assets/css/vich_image.scss
  templates/worker.html.twig
Labels: Reviewed by PO

#274 Sprint05 us100
  src/Controller/AdvertiseController.php
  src/Entity/Advertise.php
  src/Form/AdvertiseType.php
  src/Migrations/Version20190107143049.php
  src/Migrations/Version20190107143338.php
  src/Migrations/Version20190107144244.php
  src/Migrations/Version20190108083122.php
  src/Repository/AdvertiseRepository.php
  templates/admin/advertise/_form.html.twig
  templates/admin/advertise/edit.html.twig
  templates/navbarAdmin.html.twig
Labels: Reviewed by PO

#282 modification des boutons et harmonisation de l'admin
  assets/css/admin.scss
  assets/css/app.scss
  templates/admin/coffee/_delete_form.html.twig
  templates/admin/coffee/_form.html.twig
  templates/admin/coffee/edit.html.twig
  templates/admin/coffee/index.html.twig
  templates/admin/coffee/new.html.twig
  templates/admin/coffee/show.html.twig
  templates/admin/infusion/_delete_form.html.twig
  templates/admin/infusion/_form.html.twig
  templates/admin/infusion/edit.html.twig
  templates/admin/infusion/index.html.twig
  templates/admin/infusion/new.html.twig
  templates/admin/infusion/show.html.twig
  templates/admin/tea/_delete_form.html.twig
  templates/admin/tea/_form.html.twig
  templates/admin/tea/edit.html.twig
  templates/admin/tea/index.html.twig
  templates/admin/tea/new.html.twig
  templates/admin/tea/show.html.twig
  templates/admin/worker/_delete_form.html.twig
  templates/admin/worker/_form.html.twig
  templates/admin/worker/edit.html.twig
  templates/admin/worker/index.html.twig
  templates/admin/worker/new.html.twig
  templates/admin/worker/show.html.twig
  templates/category/_delete_form.html.twig
  templates/category/_form.html.twig
  templates/category/edit.html.twig
  templates/category/index.html.twig
  templates/category/new.html.twig
  templates/category/show.html.twig
  templates/security/login.html.twig
Labels: CONFLICT RESOLVED, Reviewed by PO

#284 changement du bg pour quelque chose de moins prononcé
  assets/css/global.scss
  assets/images/homeImages/padded-light.png
Labels: Reviewed by PO

#287 hamonisation de la pasge contact
  assets/css/schedule.scss
  templates/contact/index.html.twig
  templates/schedule.html.twig
Labels: Reviewed by PO

#289 maj de l'image du personnel
  assets/images/homeImages/worker.jpg
  templates/worker.html.twig
Labels: Reviewed by PO

#291 Fix photo equipe2
  assets/css/global.scss
Labels: Reviewed by PO

#293 Fix_annonce_admin_flash
  src/Controller/AdvertiseController.php
Labels: Reviewed by PO

#295 Fix tures
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/CoffeeFixtures.php
  src/DataFixtures/InfusionFixtures.php
  src/DataFixtures/ShelfFixtures.php
  src/DataFixtures/TeaFixtures.php
  src/DataFixtures/UserFixtures.php
  src/DataFixtures/WorkerFixtures.php
Labels: Reviewed by PO

#292 Fix boutons
  templates/admin/advertise/_form.html.twig
  templates/admin/advertise/edit.html.twig
  templates/admin/coffee/index.html.twig
  templates/admin/infusion/index.html.twig
  templates/admin/tea/index.html.twig
  templates/admin/tea/show.html.twig
  templates/category/new.html.twig
Labels: Reviewed by PO

#298 SPRINT08_US101
  assets/css/advertise.scss
  assets/css/app.scss
  src/Controller/HomeController.php
  src/Migrations/Version20190108093605.php
  src/Migrations/Version20190108150138.php
  templates/advertise.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
Labels: Correction Done, Reviewed by PO

#299 S8us112
  src/Controller/InfusionCategoryController.php
  src/Entity/FamilyInfusion.php
  src/Entity/FamilyTea.php
  src/Entity/Infusion.php
  src/Migrations/Version20190108101534.php
  src/Migrations/Version20190108102351.php
  src/Migrations/Version20190108161723.php
  src/Migrations/Version20190108162429.php
  src/Migrations/Version20190108164723.php
  src/Migrations/Version20190108164827.php
  src/Repository/FamilyInfusionRepository.php
  templates/infusion_category/index.html.twig
  templates/infusion_category/show.html.twig
  templates/navbar.html.twig
Labels: Reviewed by PO

#310 SPRINT05_US03
  assets/css/app.scss
  assets/css/novelty.scss
  assets/images/infusionImages/infusion.jpg
  assets/images/teaImages/the.jpg
  src/Controller/HomeController.php
  src/Service/MaxProductChecker.php
  templates/home/index.html.twig
  templates/novelty.html.twig
Labels: CONFLICT RESOLVED, Reviewed by PO

#312 Ajout de l'unique entity sur les catégories
  src/Entity/Category.php
Labels: Reviewed by PO

#313 Fix base
  templates/base.html.twig
Labels: Reviewed by PO

#314 Fix page edit entity admin
  src/Entity/Category.php
  src/Entity/Coffee.php
  src/Entity/Infusion.php
  src/Entity/Tea.php
  src/Entity/Worker.php
Labels: Reviewed by PO

#315 S08us117
  src/Form/InfusionType.php
  templates/admin/infusion/index.html.twig
  templates/admin/infusion/show.html.twig
Labels: Reviewed by PO

#316 Fix size h1 admin
  assets/css/admin.scss
  templates/admin/advertise/edit.html.twig
  templates/admin/coffee/edit.html.twig
  templates/admin/coffee/index.html.twig
  templates/admin/coffee/new.html.twig
  templates/admin/coffee/show.html.twig
  templates/admin/infusion/edit.html.twig
  templates/admin/infusion/index.html.twig
  templates/admin/infusion/new.html.twig
  templates/admin/infusion/show.html.twig
  templates/admin/tea/edit.html.twig
  templates/admin/tea/index.html.twig
  templates/admin/tea/new.html.twig
  templates/admin/tea/show.html.twig
  templates/admin/worker/edit.html.twig
  templates/admin/worker/index.html.twig
  templates/admin/worker/new.html.twig
  templates/admin/worker/show.html.twig
  templates/admin_home/index.html.twig
  templates/category/edit.html.twig
  templates/category/index.html.twig
  templates/category/new.html.twig
  templates/category/show.html.twig
  templates/security/login.html.twig
Labels: Reviewed by PO

#317 harmonisation du schedule et de la map sur la page contact
  assets/css/map.scss
  assets/css/schedule.scss
  templates/contact/index.html.twig
Labels: Reviewed by PO

#320 Tea title
  assets/css/admin.scss
  templates/admin/advertise/edit.html.twig
  templates/admin/coffee/edit.html.twig
  templates/admin/coffee/index.html.twig
  templates/admin/coffee/new.html.twig
  templates/admin/coffee/show.html.twig
  templates/admin/infusion/edit.html.twig
  templates/admin/infusion/index.html.twig
  templates/admin/infusion/new.html.twig
  templates/admin/infusion/show.html.twig
  templates/admin/tea/edit.html.twig
  templates/admin/tea/index.html.twig
  templates/admin/tea/new.html.twig
  templates/admin/tea/show.html.twig
  templates/admin/worker/edit.html.twig
  templates/admin/worker/index.html.twig
  templates/admin/worker/new.html.twig
  templates/admin/worker/show.html.twig
  templates/admin_home/index.html.twig
  templates/category/edit.html.twig
  templates/category/index.html.twig
  templates/category/new.html.twig
  templates/category/show.html.twig
  templates/security/login.html.twig
  templates/teaCategory/index.html.twig
Labels: Reviewed by PO

#323 modification du chemin du placeholder de png en jpg et suppression de…
  templates/navbar.html.twig
  templates/worker.html.twig
Labels: Reviewed by PO

#327 Fix infusion
  src/Controller/InfusionCategoryController.php
Labels: Reviewed by PO

#322 Fix admin
  assets/css/global.scss
  src/Entity/Tea.php
  templates/admin/advertise/_form.html.twig
  templates/admin/advertise/edit.html.twig
  templates/admin/coffee/edit.html.twig
  templates/admin/coffee/index.html.twig
  templates/admin/infusion/edit.html.twig
  templates/admin/infusion/index.html.twig
  templates/admin/tea/edit.html.twig
  templates/admin/tea/index.html.twig
  templates/admin/worker/edit.html.twig
  templates/admin/worker/index.html.twig
  templates/category/edit.html.twig
  templates/category/index.html.twig
  templates/navbarAdmin.html.twig
Labels: Reviewed by PO

#325 Style category cafe
  assets/css/category.scss
  src/Controller/CoffeeCategoryController.php
  templates/coffee_category/index.html.twig
Labels: CONFLICT RESOLVED, Reviewed by PO

#326 FixStyleCategoryInfusion
  assets/css/category.scss
  templates/infusion_category/index.html.twig
Labels: CONFLICT RESOLVED, Reviewed by PO

#328 FixDetailInfusion
  templates/infusion_category/show.html.twig
Labels: Reviewed by PO

#330 fix bug infusion
  src/Entity/Infusion.php
Labels: Reviewed by PO

#329 FixStyleDetailTea
  templates/teaCategory/show.html.twig
Labels: Reviewed by PO

#331 Fix category cafe
  src/Migrations/Version20181129154811.php
  templates/coffee_category/index.html.twig
Labels: Reviewed by PO

#332 Fix banner
  assets/css/banner.scss
  assets/images/banner/logocafeblanc.png
  assets/images/banner/mtf11.png
  templates/banner.html.twig
Labels: Reviewed by PO

#333 Dev
  assets/css/banner.scss
  assets/css/category.scss
  assets/css/global.scss
  assets/images/banner/logocafeblanc.png
  assets/images/banner/mtf11.png
  src/Controller/CoffeeCategoryController.php
  src/Controller/InfusionCategoryController.php
  src/Entity/Infusion.php
  src/Entity/Tea.php
  src/Migrations/Version20181129154811.php
  templates/admin/advertise/_form.html.twig
  templates/admin/advertise/edit.html.twig
  templates/admin/coffee/edit.html.twig
  templates/admin/coffee/index.html.twig
  templates/admin/infusion/edit.html.twig
  templates/admin/infusion/index.html.twig
  templates/admin/tea/edit.html.twig
  templates/admin/tea/index.html.twig
  templates/admin/worker/edit.html.twig
  templates/admin/worker/index.html.twig
  templates/banner.html.twig
  templates/category/edit.html.twig
  templates/category/index.html.twig
  templates/coffee_category/index.html.twig
  templates/infusion_category/index.html.twig
  templates/infusion_category/show.html.twig
  templates/navbar.html.twig
  templates/navbarAdmin.html.twig
  templates/teaCategory/index.html.twig
  templates/teaCategory/show.html.twig
  templates/worker.html.twig
Labels: Reviewed by PO

#334 SPRINT05_US04
  src/Controller/HomeController.php
  src/Migrations/Version20190109153431.php
  src/Service/MaxProductChecker.php
  templates/highlighted.html.twig
  templates/home/index.html.twig
Labels: Reviewed by PO

#335 Fix boxshadow
  assets/css/global.scss
Labels: Reviewed by PO

#336 Fix banner logo
  assets/images/banner/logo_ww.png
  assets/images/banner/mtf11.png
  templates/banner.html.twig
Labels: Reviewed by PO

#337 fix style page accueil
  assets/css/advertise.scss
  assets/css/novelty.scss
  src/Migrations/Version20190109164704.php
  src/Migrations/Version20190110085505.php
  src/Migrations/Version20190110093755.php
  src/Migrations/Version20190110102545.php
  templates/novelty.html.twig
Labels: Reviewed by PO

#338 fixTea
  templates/teaCategory/index.html.twig
  templates/teaCategory/show.html.twig
Labels: Reviewed by PO

#339 FIX_INDEX_ORDRE_APHA
  src/Controller/CategoryController.php
  src/Controller/CoffeeController.php
  src/Controller/InfusionController.php
  src/Controller/WorkerController.php
Labels: Reviewed by PO

#340 ajout des titres et famille
  templates/admin/coffee/index.html.twig
  templates/admin/infusion/index.html.twig
  templates/admin/tea/index.html.twig
Labels: Reviewed by PO

#341 ajout du help pour le uniqTitle
  src/Form/CategoryType.php
Labels: Reviewed by PO

#342 FixTISANE
  templates/infusion_category/index.html.twig
  templates/infusion_category/show.html.twig
Labels: Reviewed by PO

#343 FIX_NOVELTY_LINKS
  templates/novelty.html.twig
Labels: Reviewed by PO

#345 échange des boutons On et Off
  templates/admin/infusion/index.html.twig
  templates/admin/tea/index.html.twig
Labels: Reviewed by PO

#346 fix card grocery accessory
  assets/css/accessory.scss
  templates/accessory/index.html.twig
  templates/grocery/index.html.twig
Labels: Reviewed by PO

#347 si note est remplie, la zone apparait
  templates/infusion_category/show.html.twig
  templates/teaCategory/show.html.twig
Labels: Reviewed by PO

#344 changement des h1
  assets/css/global.scss
  templates/accessory/index.html.twig
  templates/coffee_category/index.html.twig
  templates/grocery/index.html.twig
  templates/infusion_category/index.html.twig
  templates/teaCategory/index.html.twig
Labels: CONFLICT RESOLVED, Reviewed by PO

#348 FIX_BUTTON_ADD_COFFEE
  templates/admin/coffee/index.html.twig
Labels: Reviewed by PO

#352 endif page show
  templates/infusion_category/show.html.twig
Labels: Reviewed by PO

#349 Fix tea infu
  assets/css/category.scss
  assets/images/infusionImages/infusionbg.jpg
  assets/images/teaImages/Teas.jpg
  src/Controller/TeaCategoryController.php
  src/Entity/Infusion.php
  src/Form/InfusionType.php
  templates/infusion_category/index.html.twig
  templates/infusion_category/show.html.twig
  templates/teaCategory/index.html.twig
  templates/teaCategory/show.html.twig
Labels: CONFLICT RESOLVED

#356 suppression des lignes en double
  templates/teaCategory/index.html.twig
  templates/teaCategory/show.html.twig
Labels: Reviewed by PO

#358 faute d'orthographe
  src/Controller/ContactController.php
Labels: Reviewed by PO

#354 Dev
  assets/css/category.scss
  assets/css/global.scss
  assets/images/infusionImages/infusionbg.jpg
  assets/images/teaImages/Teas.jpg
  src/Controller/ContactController.php
  src/Controller/TeaCategoryController.php
  src/Entity/Infusion.php
  src/Form/InfusionType.php
  templates/accessory/index.html.twig
  templates/admin/coffee/index.html.twig
  templates/coffee_category/index.html.twig
  templates/grocery/index.html.twig
  templates/infusion_category/index.html.twig
  templates/infusion_category/show.html.twig
  templates/teaCategory/index.html.twig
  templates/teaCategory/show.html.twig
Labels: Reviewed by PO

#360 FIX_HR_PRODUITS_MOIS
  templates/highlighted.html.twig
Labels: Reviewed by PO

#355 responsive Accessoire et epicerie
  assets/css/accessory.scss
  templates/grocery/index.html.twig
  templates/teaCategory/index.html.twig
Labels: CONFLICT RESOLVED

#361 responsive ok
  assets/css/accessory.scss
  templates/coffee_category/index.html.twig
Labels: CONFLICT RESOLVED

#362 Highlighted décalé
  templates/highlighted.html.twig
Labels: Reviewed by PO

#357 ajout des placeholder
  assets/css/category.scss
  assets/images/coffeeImages/coffees.jpg
  assets/images/teaImages/Teas.jpg
  templates/coffee_category/index.html.twig
  templates/novelty.html.twig
  templates/teaCategory/index.html.twig
Labels: CONFLICT RESOLVED

#359 correction edit categorie
  assets/css/category.scss
  src/Controller/CategoryController.php
  templates/category/_delete_form.html.twig
  templates/category/edit.html.twig
Labels: CONFLICT RESOLVED

#365 correction w3c accueil
  assets/css/novelty.scss
  assets/css/schedule.scss
  templates/advertise.html.twig
  templates/base.html.twig
  templates/footer.html.twig
  templates/highlighted.html.twig
  templates/novelty.html.twig
  templates/schedule.html.twig
Labels: Reviewed by PO

#366 modification du scss accessory
  assets/css/accessory.scss
Labels: Reviewed by PO

#368 changement class img
  templates/coffee_category/show.html.twig
  templates/teaCategory/index.html.twig
Labels: Reviewed by PO

#370 teavalidateur
  templates/grocery/index.html.twig
Labels: Reviewed by PO

#369 validator cafe
  templates/coffee_category/index.html.twig
Labels: CONFLICT RESOLVED

#371 validator accessoires
  templates/accessory/index.html.twig
Labels: Reviewed by PO

#373 Dev
  assets/css/accessory.scss
  assets/css/banner.scss
  assets/css/category.scss
  assets/css/novelty.scss
  assets/css/schedule.scss
  assets/images/coffeeImages/coffees.jpg
  assets/images/logo/favicon.ico
  assets/images/teaImages/Teas.jpg
  src/Controller/CategoryController.php
  templates/accessory/index.html.twig
  templates/advertise.html.twig
  templates/banner.html.twig
  templates/base.html.twig
  templates/category/_delete_form.html.twig
  templates/category/edit.html.twig
  templates/coffee_category/index.html.twig
  templates/coffee_category/show.html.twig
  templates/footer.html.twig
  templates/grocery/index.html.twig
  templates/highlighted.html.twig
  templates/infusion_category/index.html.twig
  templates/infusion_category/show.html.twig
  templates/novelty.html.twig
  templates/schedule.html.twig
  templates/story.html.twig
  templates/teaCategory/index.html.twig
  templates/teaCategory/show.html.twig
Labels: Reviewed by PO

#372 FIX_RESPONSIVE_HOME
  assets/css/advertise.scss
  assets/css/banner.scss
  assets/css/global.scss
Labels: CONFLICT RESOLVED, Reviewed by PO

#376 retour de la condition feature
  assets/css/accessory.scss
  templates/infusion_category/show.html.twig
  templates/teaCategory/show.html.twig
Labels: Reviewed by PO

#377 changement du chemin du logo
  templates/banner.html.twig
Labels: Reviewed by PO

#380 fix img grocery & card height accessory
  templates/accessory/index.html.twig
  templates/grocery/index.html.twig
Labels: Reviewed by PO

#381 changement du placeholder sur l'index coffee
  templates/coffee_category/index.html.twig
Labels: Reviewed by PO

#383 suprresion d'une /div en trop
  templates/teaCategory/index.html.twig
Labels: Reviewed by PO

#297 mise en place de la modal des mentions légales
  assets/css/footer.scss
  templates/footer.html.twig
Labels: CONFLICT RESOLVED, Reviewed by PO

#386 Fix assert
  src/Entity/Contact.php
Labels: Reviewed by PO

#387 Fix map
  templates/contact/index.html.twig
Labels: Reviewed by PO

#388 fix color border
  assets/css/map.scss
Labels: Reviewed by PO

#390 Create README.md
  README.md
Labels: Reviewed by PO

#391 Dev
  README.md
Labels: Reviewed by PO

#392 Fix text
  templates/story.html.twig
Labels: Reviewed by PO

#393 Fix reponsive grocery accessory coffee tea
  assets/css/accessory.scss
  assets/css/global.scss
  templates/accessory/index.html.twig
  templates/coffee_category/index.html.twig
  templates/grocery/index.html.twig
  templates/teaCategory/index.html.twig
Labels: Reviewed by PO

#394 fix banner
  assets/css/banner.scss
  templates/banner.html.twig
Labels: Reviewed by PO

#395 Dev
  assets/css/accessory.scss
  assets/css/banner.scss
  assets/css/global.scss
  templates/accessory/index.html.twig
  templates/banner.html.twig
  templates/coffee_category/index.html.twig
  templates/grocery/index.html.twig
  templates/story.html.twig
  templates/teaCategory/index.html.twig
Labels: Reviewed by PO
